# Generated by Django 6.0.6 on 2026-07-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile'),
        ('shop', '0002_commissionplan_orderitem_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='commission_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='shop.commissionplan'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='accounts.user'),
        ),
    ]
