# Generated by Django 6.0.6 on 2026-07-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login'),
        ('shop', '0010_shipment_vendorstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('commission_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional % override; blank uses plan default.', max_digits=5, null=True)),
                ('payout_method', models.CharField(default='bank_transfer', max_length=50)),
                ('payout_details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('commission_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_accounts', to='shop.commissionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to='accounts.user')),
            ],
            options={
                'db_table': 'seller_accounts',
            },
        ),
    ]
