# Generated by Django 6.0.6 on 2026-07-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='setup_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='subscription_last_charged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='setup_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_last_charged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
