/**
 * Editorial roadmap — production planning data (not spam content).
 * Use to prioritize CMS blog posts, FAQs, landing pages, and downloads.
 * Titles are briefs for human editors; publish only helpful, accurate articles.
 */

import type { Intent } from './topic-clusters'

export type RoadmapItem = {
  id: string
  title: string
  slug: string
  category: string
  intent: Intent
  clusterId: string
  format: 'article' | 'faq' | 'landing' | 'comparison' | 'guide' | 'download'
  priority: 'P0' | 'P1' | 'P2'
  status: 'planned' | 'draft' | 'published'
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80)
}

const ARTICLE_SEEDS: Array<{ clusterId: string; category: string; titles: string[] }> = [
  {
    clusterId: 'nfc-pet-tags',
    category: 'NFC & Smart Tags',
    titles: [
      'NFC Pet Tags 101 for First-Time Owners',
      'How to Activate a KediSmart Tag',
      'Best Practices for Collar Tag Placement',
      'NFC Tag Care: Cleaning and Inspection',
      'Why Dual NFC and QR Beats Single-Tech Tags',
      'Smart Tags for Cats: Breakaway Collar Tips',
      'Smart Tags for Dogs: Sizing by Breed',
      'Updating Your Digital Pet Profile After a Move',
      'Lost Mode Explained: When and How to Enable It',
      'Anonymous Finder Messaging: Privacy Guide',
      'Waterproof Ratings Explained for Pet Tags',
      'Do Smart Tags Work in Rain and Mud?',
      'Choosing Tag Color for Visibility at Night',
      'Backup Contacts on Digital Pet IDs',
      'How Shelters Benefit from Scannable Tags',
      'Apartment Living: Tags for Balcony Escape Risks',
      'Multi-Pet Households: Organizing Profiles',
      'Gift Guide: Smart Tags for New Pet Parents',
      'Common Myths About NFC Pet Tags',
      'How Fast Can a Finder Reach You?',
      'Tag + Microchip: Layered Identification Plan',
      'Travel Days: Temporary Profile Notes',
      'Senior Pets and Medical Notes on Tags',
      'Puppies and Growing Necks: Adjustable Collars',
      'Kitten Safety Collars and Digital IDs',
    ],
  },
  {
    clusterId: 'lost-pet-recovery',
    category: 'Lost Pet Recovery',
    titles: [
      'First Hour Checklist When a Dog Goes Missing',
      'First Hour Checklist When a Cat Goes Missing',
      'How to Search High-Rise Buildings for Pets',
      'Neighborhood Alert Templates That Work',
      'What Photos Help Finders Recognize Your Pet',
      'When to Call Vets and Shelters',
      'Night Search Tips for Missing Dogs',
      'Why Cats Hide Nearby After Escaping',
      'Using Lost Mode Without Panicking',
      'Safe Meetup Practices After a Finder Contact',
      'Preventing a Second Escape After Reunion',
      'Monsoon Season Lost-Pet Risks in Bangladesh',
      'Festival Noise and Pet Escape Prevention',
      'Working with Building Security on Lost Pets',
      'Community WhatsApp Groups: What to Post',
      'Flyer Design Basics for Lost Pets',
      'How Long to Keep Searching Locally',
      'Emotional Care for Owners During a Search',
      'Found a Pet? How to Help Responsibly',
      'What Not to Do When You Find a Stray',
      'Documenting Sightings on a Map',
      'When to Escalate to Wider Alerts',
      'Microchip Registry Updates After a Move',
      'Reunion Stories: What Actually Worked',
      'Building a Family Lost-Pet Playbook',
    ],
  },
  {
    clusterId: 'pet-identification',
    category: 'Pet Identification',
    titles: [
      'Pet ID Options Compared in Plain Language',
      'How Microchips Are Implanted',
      'Updating Microchip Registry Contacts',
      'Why Phone Numbers on Tags Become Stale',
      'Digital IDs for Multi-Owner Households',
      'ID for Adopted Pets with Unknown History',
      'Breeders: Sending Pets Home with Digital IDs',
      'Clinic Intake: What ID Speeds Care',
      'Travel Documents vs Everyday ID',
      'Visible Name Tags vs Private Contact Tags',
      'ID for Small Dogs and Toy Breeds',
      'ID for Large Breeds with Heavy Collars',
      'Bird and Exotic Pet Identification Basics',
      'Rabbits and Small Mammals: ID Challenges',
      'How to Test Your Tag Before You Need It',
      'Quarterly ID Audit Checklist',
      'Kids and Pet ID: Teaching What to Do',
      'Domestic Help and Pet Emergency Access',
      'Photo ID Best Practices for Profiles',
      'Name Spelling Consistency Across Records',
      'Secondary Contact: When Owners Are Abroad',
      'ID After Surgery or Cone Use',
      'Swimmer Pets and Tag Security',
      'Reflective Tags for Night Walks',
      'Choosing Engraving Languages (EN/BN)',
    ],
  },
  {
    clusterId: 'cat-safety',
    category: 'Cat Safety',
    titles: [
      'Balcony Netting for Urban Cats',
      'Toxic Plants Common in Bangladeshi Homes',
      'Window Screens That Actually Hold',
      'Cat Carrier Training Without Stress',
      'Litter Box Placement and Escape Routes',
      'Keeping Cats Indoors During Heat Waves',
      'Cat-Proofing Electrical Cords',
      'Vertical Space for Indoor Enrichment',
      'Introducing a New Cat Safely',
      'Multi-Cat Household Peace Tips',
      'Outdoor Supervision with Harnesses',
      'Feral Cat Care vs Owned Cat Safety',
      'Vaccination Timing for Outdoor Access',
      'Parasite Prevention Calendar',
      'Signs Your Cat Is Stressed',
      'Nighttime Roaming Risks',
      'Food Safety: Human Foods Cats Must Avoid',
      'Water Intake Tips in Hot Weather',
      'Carrier Ready for Sudden Vet Trips',
      'ID for Indoor-Only Cats Who Still Escape',
      'Kitten-Proofing a New Apartment',
      'Senior Cat Mobility and Home Safety',
      'Declawing Myths and Humane Alternatives',
      'Cat Bite Wound First Response',
      'When to Emergency-Visit for Cats',
    ],
  },
  {
    clusterId: 'dog-safety',
    category: 'Dog Safety',
    titles: [
      'Leash Skills That Prevent Door Bolts',
      'Dhaka Traffic Awareness for Dog Walkers',
      'Paw Pad Care on Hot Pavement',
      'Muzzle Training for Vet Visits',
      'Recall Training Basics',
      'Dog Park Etiquette and Risk Reduction',
      'Puppy Socialization Without Overload',
      'Reactive Dog Walking Strategies',
      'Crate Training for Safety',
      'Home Alone: Reducing Escape Anxiety',
      'Monsoon Walks: Drying and Skin Care',
      'Street Dog Interactions on Walks',
      'Choosing the Right Harness Fit',
      'Collar vs Harness for Pullers',
      'Night Walk Visibility Gear',
      'Water Safety for Dogs Who Swim',
      'Heat Exhaustion First Aid Overview',
      'Toxic Foods Dogs Must Never Eat',
      'Toy Safety and Choking Hazards',
      'Fencing and Yard Escape Points',
      'Guest Protocols to Prevent Door Dashes',
      'Car Restraint Options Compared',
      'Working Breeds and Mental Enrichment',
      'Senior Dog Slippery Floor Safety',
      'When Limping Needs Same-Day Care',
    ],
  },
  {
    clusterId: 'pet-health-records',
    category: 'Pet Health Records',
    titles: [
      'Building a Vaccination Timeline',
      'What Clinics Expect at First Visit',
      'Storing Prescription Histories',
      'Allergy Logs That Help Dermatologists',
      'Weight Tracking and Body Condition',
      'Dental Records and Home Care Notes',
      'Surgery Summaries Owners Should Keep',
      'Lab Result Filing System',
      'Sharing Records When Changing Vets',
      'Digital vs Paper: Hybrid Workflow',
      'Emergency Card One-Pager Template',
      'Medication Schedules for Busy Families',
      'Chronic Disease Journals',
      'Parasite Prevention Proof for Boarding',
      'Insurance Claims and Document Packs',
      'Exporting Records Before Travel',
      'Photo Documentation of Skin Issues',
      'Behavior Notes Relevant to Care',
      'Spay/Neuter Certificate Storage',
      'Microchip Number Where to Record It',
      'Blood Type Notes for Transfusion Risk Breeds',
      'Aging Milestones to Track',
      'Nutrition Changes Log',
      'Second Opinion Packets',
      'Annual Wellness Checklist',
    ],
  },
  {
    clusterId: 'pet-travel',
    category: 'Pet Travel',
    titles: [
      'Weekend Road Trips with Dogs',
      'Cat Carrier Acclimation Plan',
      'Hotel Pet Policies: What to Ask',
      'Packing Medications for Trips',
      'Motion Sickness Signs and Prep',
      'Rest Stop Safety Protocols',
      'Airline Pet Rules Overview (Research First)',
      'Bus and Train Realities with Pets',
      'Crossing Districts: Local Regulations Check',
      'Temporary Tags for Travel Sitters',
      'Boarding vs Pet Sitters Comparison',
      'Leaving Pets Home: Sitter Brief Template',
      'Heat Risk on Summer Car Trips',
      'Winter/Night Travel Visibility',
      'Portable Water Systems That Work',
      'First Aid Kit for Pet Travel',
      'Calming Strategies Without Sedation Myths',
      'Document Folder for Clinic Stops En Route',
      'Photo of Pet on Your Phone Lock Screen',
      'Lost-Pet Plan Away from Home',
      'Camping with Dogs: Tick and Leash Rules',
      'Beach Trips: Paw and Salt Water Care',
      'Visiting Family: Introducing Pets to New Homes',
      'Return Home Decompression Tips',
      'International Moves: Start Research Early',
    ],
  },
  {
    clusterId: 'pet-ownership',
    category: 'Pet Ownership',
    titles: [
      'Are You Ready for a Pet? Honest Checklist',
      'Budgeting for the First Year',
      'Choosing Cat vs Dog for Apartments',
      'Adoption vs Purchase Ethics',
      'Puppy Proofing Room by Room',
      'Kitten Proofing Room by Room',
      'Finding a Primary Vet Before Day One',
      'Pet-Friendly Rental Conversations',
      'Teaching Children Gentle Handling',
      'Time Commitments by Species',
      'Enrichment on a Budget',
      'Socialization Windows Explained',
      'When Behavior Needs a Professional',
      'End-of-Life Planning Is Kindness',
      'Pet Trusts and Emergency Caregivers',
      'Work-from-Home vs Office Schedules',
      'Second Pet Decision Framework',
      'Species-Appropriate Diets Overview',
      'Grooming Routines by Coat Type',
      'Community Resources in Dhaka',
      'Volunteer and Foster Pathways',
      'Avoiding Impulse Buys During Holidays',
      'Reading Pet Body Language Basics',
      'Building a Home Care Calendar',
      'Celebrating Milestones Responsibly',
    ],
  },
]

/** 200+ planned blog/article briefs across clusters. */
export const PLANNED_ARTICLES: RoadmapItem[] = ARTICLE_SEEDS.flatMap((seed, si) =>
  seed.titles.map((title, ti) => ({
    id: `article-${seed.clusterId}-${ti}`,
    title,
    slug: slugify(title),
    category: seed.category,
    intent: 'informational' as Intent,
    clusterId: seed.clusterId,
    format: 'article' as const,
    priority: (ti < 5 ? 'P0' : ti < 12 ? 'P1' : 'P2') as RoadmapItem['priority'],
    status: 'planned' as const,
  })),
)

const FAQ_TEMPLATES: Array<{ clusterId: string; category: string; qas: [string, string][] }> = [
  {
    clusterId: 'nfc-pet-tags',
    category: 'NFC Tags',
    qas: [
      ['What is an NFC pet tag?', 'A wearable chip that opens a digital pet profile when tapped with a phone.'],
      ['Do finders need an app?', 'No. The profile opens in a mobile browser via NFC or QR.'],
      ['Is my phone number public?', 'Not by default. You control visibility and can use anonymous messaging.'],
      ['What if a phone has no NFC?', 'Use the QR code printed on the tag.'],
      ['Are tags waterproof?', 'Quality sealed tags tolerate rain and baths; inspect regularly.'],
      ['Can cats wear smart tags?', 'Yes, with a correctly sized breakaway collar.'],
      ['Does NFC drain my phone?', 'The tag is passive and uses negligible phone energy during a tap.'],
      ['How do I update details?', 'Edit the pet profile in your KediSmart account; the tag URL stays the same.'],
      ['What is lost mode?', 'A status that signals the pet is missing and enables finder contact flows.'],
      ['Can one account manage multiple pets?', 'Yes. Create a profile per pet and assign tags accordingly.'],
      ['Will metal collars block NFC?', 'Sometimes. Keep the chip face accessible and test after fitting.'],
      ['How often should I test the tag?', 'Monthly, and before travel.'],
      ['What if the QR wears off?', 'Replace the tag; keep the same digital profile when possible.'],
      ['Is GPS included?', 'No. NFC/QR tags are identification links, not live trackers.'],
      ['Do shelters recognize smart tags?', 'Any staff with a phone can open the profile; educate locally when possible.'],
    ],
  },
  {
    clusterId: 'lost-pet-recovery',
    category: 'Lost Pets',
    qas: [
      ['What should I do first if my pet is lost?', 'Search nearby immediately, alert neighbors, and enable lost mode on the digital profile.'],
      ['Should I drive far right away?', 'Exhaust the local radius first; most pets are close initially.'],
      ['Where do I report in Bangladesh?', 'Local vets, shelters, building security, and community groups — plus your KediSmart profile.'],
      ['Should I leave food outside for a lost cat?', 'Near the exit point, yes — cats often hide nearby.'],
      ['How do I meet a finder safely?', 'Public place, daylight, bring ID for the pet, and avoid sharing home address early.'],
      ['What if someone demands money?', 'Prioritize pet safety; involve local authorities if you suspect extortion.'],
      ['How long should lost mode stay on?', 'Until reunion, then disable and thank helpers.'],
      ['Do I post on every social network?', 'Prefer accurate local posts over spam across irrelevant groups.'],
      ['Should children search alone?', 'No. Adults should lead searches near roads.'],
      ['What details belong on a flyer?', 'Clear photo, name, area last seen, and secure contact channel.'],
      ['Can heat affect search timing?', 'Yes. Search early morning and evening in hot months; protect yourself too.'],
      ['What if my pet has no tag?', 'Still search and alert; get layered ID after reunion.'],
      ['Should I wait 24 hours?', 'No. Start within minutes.'],
    ],
  },
]

/** Expand FAQ templates + generated variants toward 100+. */
function buildFaqs(): RoadmapItem[] {
  const items: RoadmapItem[] = []
  let n = 0
  for (const block of FAQ_TEMPLATES) {
    for (const [q, a] of block.qas) {
      items.push({
        id: `faq-${n++}`,
        title: q,
        slug: slugify(q),
        category: block.category,
        intent: 'informational',
        clusterId: block.clusterId,
        format: 'faq',
        priority: 'P0',
        status: 'planned',
      })
      // Store answer in title companion via separate export below
      void a
    }
  }

  const species = ['dogs', 'cats', 'puppies', 'kittens', 'senior dogs', 'senior cats']
  const topics = [
    'vaccination schedules',
    'heat safety',
    'monsoon care',
    'apartment living',
    'first vet visit',
    'nutrition basics',
    'grooming frequency',
    'travel readiness',
    'ID tag checks',
    'emergency go-bags',
    'parasite prevention',
    'dental care',
    'exercise needs',
    'enrichment ideas',
    'carrier training',
  ]
  for (const sp of species) {
    for (const topic of topics) {
      if (items.filter((i) => i.format === 'faq').length >= 100) break
      const title = `FAQ: ${topic} for ${sp}?`
      items.push({
        id: `faq-${n++}`,
        title,
        slug: slugify(title),
        category: 'Pet Care FAQ',
        intent: 'informational',
        clusterId: sp.includes('cat') ? 'cat-safety' : 'dog-safety',
        format: 'faq',
        priority: 'P1',
        status: 'planned',
      })
    }
  }
  return items.slice(0, 100)
}

export const PLANNED_FAQS = buildFaqs()

/** Published FAQ answers paired with help-center expansion. */
export const FAQ_ANSWERS: { question: string; answer: string; clusterId: string }[] =
  FAQ_TEMPLATES.flatMap((b) =>
    b.qas.map(([question, answer]) => ({ question, answer, clusterId: b.clusterId })),
  )

const LANDING_TITLES = [
  'NFC Pet Tags in Bangladesh',
  'Smart Pet Tags for Dogs',
  'Smart Pet Tags for Cats',
  'Digital Pet ID Platform',
  'Lost Pet Recovery Hub',
  'Pet Emergency Information Center',
  'Waterproof Pet Tags',
  'QR Pet Tags',
  'Pet Identification Guide Hub',
  'Cat Safety Resources',
  'Dog Safety Resources',
  'Pet Health Records Hub',
  'Pet Travel Hub Bangladesh',
  'Responsible Pet Ownership Hub',
  'Find a Vet in Dhaka',
  'Live Animals Marketplace Overview',
  'Pet Products Shop Overview',
  'KediSmart for Breeders',
  'KediSmart for Veterinarians',
  'KediSmart for Pet Parents',
  'NFC Tag Setup Landing',
  'Lost Mode Explained Landing',
  'Anonymous Messaging Landing',
  'Multi-Pet Households',
  'Apartment Pet Safety',
  'Monsoon Pet Care Landing',
  'Heat Safety Landing',
  'First-Time Cat Owner Landing',
  'First-Time Dog Owner Landing',
  'Adoption Readiness Landing',
  'Pet Microchip Education',
  'Collar Tag Best Practices',
  'Shelter Partnership Landing',
  'Community Lost Pet Network',
  'Emergency Vet Directory Landing',
  'Pet Care Guides Index',
  'Compare Pet ID Technologies',
  'Bangladesh Pet Marketplace',
  'Gulshan Pet Services',
  'Family Pet Safety Plan',
  'Digital Profile Privacy Landing',
  'Tag Testing Checklist Landing',
  'Reunion Success Stories Hub',
  'Pet Travel Documents Primer',
  'Vaccination Record Landing',
  'Senior Pet Care Landing',
  'Puppy Starter Landing',
  'Kitten Starter Landing',
  'Outdoor Cat Risk Landing',
  'Dog Walking Safety Landing',
]

export const PLANNED_LANDINGS: RoadmapItem[] = LANDING_TITLES.map((title, i) => ({
  id: `landing-${i}`,
  title,
  slug: slugify(title),
  category: 'Landing Pages',
  intent: i % 3 === 0 ? 'commercial' : 'informational',
  clusterId: TOPIC_FALLBACK(i),
  format: 'landing',
  priority: i < 10 ? 'P0' : 'P1',
  status: 'planned',
}))

function TOPIC_FALLBACK(i: number): string {
  const ids = [
    'nfc-pet-tags',
    'lost-pet-recovery',
    'pet-identification',
    'cat-safety',
    'dog-safety',
    'pet-health-records',
    'pet-travel',
    'pet-ownership',
  ]
  return ids[i % ids.length]
}

const COMPARE_EXTRAS = [
  'GPS Tracker vs NFC Tag',
  'AirTag-style Trackers vs Pet Smart Tags',
  'Breakaway vs Non-breakaway Collars',
  'Harness vs Collar for City Dogs',
  'Metal Tag vs Silicone Tag',
  'Private Profile vs Public Phone Number',
  'Clinic Microchip Brands Overview',
  'Pet Insurance vs Emergency Fund',
  'Boarding vs In-Home Sitting',
  'Dry Food vs Wet Food Basics',
  'Raw Diets vs Commercial Diets (Overview)',
  'Indoor Enrichment vs Outdoor Access',
  'Puppy Classes vs Solo Training',
  'Online Vet Advice vs In-Clinic Visits',
  'Same-Day Delivery vs Pickup',
  'COD vs Online Payment for Pet Orders',
  'Marketplace Adoption vs Breeder Purchase',
  'Local Shelter vs Private Rescue',
  'Cat Tree vs Wall Shelves',
  'Clicker Training vs Lure Training',
  'Front-clip vs Back-clip Harness',
  'Soft Carrier vs Hard Carrier',
  'Reflective Gear vs Light Attachments',
  'Monthly Flea Prevention Options Overview',
  'Annual vs Triennial Vaccines Overview',
  'City Vet vs Mobile Vet',
  'Daycare vs Dog Walker',
  'Crate vs Playpen',
  'Automatic Feeder vs Scheduled Feeding',
  'Filtered Water Fountain vs Bowl',
  'Stainless vs Ceramic Bowls',
  'Nail Clippers vs Grinders',
  'Slicker Brush vs Comb',
  'Training Treats vs Regular Kibble Rewards',
  'Long Line vs Standard Leash',
  'Martingale vs Flat Collar',
  'GPS Subscription Cost vs Tag ID Value',
  'Engraved Name Only vs Full Phone Number',
  'Single Pet Profile vs Family Sharing',
  'Bengali vs English Tag Engraving',
  'Kitten Collars vs Adult Cat Collars',
  'Large Breed Tags vs Small Breed Tags',
  'Travel Carrier Sizing Compared',
  'Heatstroke Risk: Brachycephalic vs Other Breeds',
  'Shelter Intake ID Methods Compared',
  'Paper Records vs App Records',
  'WhatsApp Alerts vs Profile Messaging',
  'Community Posting vs Paid Boosts',
  'DIY Lost Flyer vs Print Shop',
  'Neighbor Network vs City-wide Alerts',
]

export const PLANNED_COMPARISONS: RoadmapItem[] = [
  ...['NFC vs QR Pet Tags', 'NFC vs Microchip', 'Smart Tag vs Engraved Collar'].map((title, i) => ({
    id: `compare-live-${i}`,
    title,
    slug: slugify(title),
    category: 'Comparisons',
    intent: 'commercial' as Intent,
    clusterId: 'nfc-pet-tags',
    format: 'comparison' as const,
    priority: 'P0' as const,
    status: 'published' as const,
  })),
  ...COMPARE_EXTRAS.map((title, i) => ({
    id: `compare-${i}`,
    title,
    slug: slugify(title),
    category: 'Comparisons',
    intent: 'informational' as Intent,
    clusterId: TOPIC_FALLBACK(i),
    format: 'comparison' as const,
    priority: (i < 10 ? 'P1' : 'P2') as RoadmapItem['priority'],
    status: 'planned' as const,
  })),
]

const GUIDE_EXTRAS = [
  'Complete NFC Setup Walkthrough',
  'Monthly Pet Safety Audit',
  'Apartment Escape Prevention Guide',
  'Monsoon Pet Care Evergreen Guide',
  'Dhaka Heat Playbook for Dog Owners',
  'Cat Enrichment Evergreen Guide',
  'Dog Enrichment Evergreen Guide',
  'Vaccination Planning Guide',
  'Parasite Prevention Evergreen',
  'Dental Care at Home Guide',
  'First Aid Overview for Pet Owners',
  'Poison Prevention Home Audit',
  'Disaster Evacuation with Pets',
  'New Baby and Pets Introduction',
  'Moving House with Pets',
  'Introducing Dogs and Cats',
  'Leash Reactivity Management Guide',
  'Litter Training Troubleshooting',
  'Crate Training Evergreen',
  'Cooperative Care Vet Training',
  'Nutrition Label Reading Guide',
  'Treat Budgeting Guide',
  'Grooming Schedule by Coat',
  'Nail Care Step-by-Step',
  'Ear Care Basics',
  'Eye Discharge When to Worry',
  'Limping Triage Overview',
  'Vomiting Triage Overview',
  'Seizure Response Overview',
  'Birthing Emergency When to Call',
  'Senior Mobility Home Mods',
  'Puppy Bite Inhibition Guide',
  'Kitten Socialization Guide',
  'Pet Sitter Brief Evergreen',
  'Boarding Prep Guide',
  'Photo ID Update Routine',
  'Family Emergency Roles Chart',
  'Kids Pet Chores Age Guide',
  'Budget Emergency Fund Guide',
  'Community Resource Mapping',
  'Shelter Volunteer Starter',
  'Foster Care Basics',
  'Breed Research Framework',
  'Allergies in the Home Guide',
  'Smoke and Festival Noise Prep',
  'Power Outage Pet Care',
  'Water Outage Hygiene Tips',
  'Travel Document Folder Guide',
  'Post-Surgery Home Care',
  'Medication Administration Tips',
]

export const PLANNED_GUIDES: RoadmapItem[] = [
  ...[
    'What Is an NFC Pet Tag?',
    'How NFC Pet Tags Work',
    'Waterproof NFC Pet Tags',
    'Lost Pet Recovery with Smart Tags',
    'Pet Emergency Information on Tags',
    'What to Do If Your Pet Is Lost',
    'How to Prepare for Pet Emergencies',
    'Pet Identification Methods Explained',
    'Digital Pet ID Explained',
    'Cat Safety Essentials',
    'Indoor vs Outdoor Cats',
    'Dog Safety Essentials',
    'Heat Safety for Dogs',
    'Pet Health Records Explained',
    'What to Include in Pet Emergency Info',
    'Pet Travel Checklist',
    'Car Travel with Pets',
    'Responsible Pet Ownership',
    'First Week with a New Pet',
  ].map((title, i) => ({
    id: `guide-live-${i}`,
    title,
    slug: slugify(title),
    category: 'Evergreen Guides',
    intent: 'informational' as Intent,
    clusterId: TOPIC_FALLBACK(i),
    format: 'guide' as const,
    priority: 'P0' as const,
    status: 'published' as const,
  })),
  ...GUIDE_EXTRAS.map((title, i) => ({
    id: `guide-${i}`,
    title,
    slug: slugify(title),
    category: 'Evergreen Guides',
    intent: 'informational' as Intent,
    clusterId: TOPIC_FALLBACK(i + 3),
    format: 'guide' as const,
    priority: 'P1' as const,
    status: 'planned' as const,
  })),
]

export const PLANNED_DOWNLOADS: RoadmapItem[] = [
  'Lost Pet Flyer Template (EN)',
  'Lost Pet Flyer Template (BN)',
  'Pet Emergency Info Card PDF',
  'Vaccination Timeline Worksheet',
  'Pet Travel Packing Checklist PDF',
  'New Pet First-Week Checklist',
  'Apartment Pet-Proofing Checklist',
  'Heat Safety Pocket Card',
  'Monsoon Care Checklist',
  'Pet Sitter Brief Template',
  'Vet Visit Question List',
  'Medication Log Sheet',
  'Weight Tracking Sheet',
  'Family Emergency Roles Poster',
  'ID Audit Quarterly Checklist',
  'Multi-Pet Profile Setup Guide PDF',
  'Finder Safety Meetup Card',
  'Neighborhood Alert Script',
  'Moving-with-Pets Planner',
  'Budget First-Year Calculator Sheet',
].map((title, i) => ({
  id: `dl-${i}`,
  title,
  slug: slugify(title),
  category: 'Downloadable Resources',
  intent: 'informational' as Intent,
  clusterId: TOPIC_FALLBACK(i),
  format: 'download' as const,
  priority: (i < 5 ? 'P0' : 'P1') as RoadmapItem['priority'],
  status: 'planned' as const,
}))

export const EDITORIAL_CATEGORIES = [
  ...new Set([
    ...PLANNED_ARTICLES.map((a) => a.category),
    ...PLANNED_FAQS.map((a) => a.category),
    ...PLANNED_LANDINGS.map((a) => a.category),
    ...PLANNED_COMPARISONS.map((a) => a.category),
    ...PLANNED_GUIDES.map((a) => a.category),
    ...PLANNED_DOWNLOADS.map((a) => a.category),
  ]),
]

export function roadmapTotals() {
  return {
    articles: PLANNED_ARTICLES.length,
    faqs: PLANNED_FAQS.length,
    landings: PLANNED_LANDINGS.length,
    comparisons: PLANNED_COMPARISONS.length,
    guides: PLANNED_GUIDES.length,
    downloads: PLANNED_DOWNLOADS.length,
    categories: EDITORIAL_CATEGORIES.length,
  }
}
