from django.urls import path

from api.views import admin, auth, blog, content, invoices, marketplace, nfc, pets, shop, users, vendor, vets

urlpatterns = [
    path("auth/register", auth.register, name="auth-register"),
    path("auth/login", auth.login, name="auth-login"),
    path("auth/staff-login", auth.staff_login, name="auth-staff-login"),
    path("auth/staff-login/start", auth.staff_login_start, name="auth-staff-login-start"),
    path("auth/staff-bridge-token", auth.staff_bridge_token, name="auth-staff-bridge-token"),
    path("auth/staff-bridge", auth.staff_bridge, name="auth-staff-bridge"),
    path("auth/refresh", auth.refresh, name="auth-refresh"),
    path("auth/logout", auth.logout, name="auth-logout"),
    path("auth/forgot-password", auth.forgot_password, name="auth-forgot-password"),
    path("auth/reset-password", auth.reset_password, name="auth-reset-password"),
    path("auth/me", auth.me, name="auth-me"),
    path("users/me", users.me, name="users-me"),
    path("users/me/profile", users.me_profile, name="users-me-profile"),
    path("users/me/change-password", users.change_password, name="users-change-password"),
    path("pets", pets.pets_list_create, name="pets-list-create"),
    path("pets/<int:pet_id>", pets.pet_detail, name="pet-detail"),
    path("pets/<int:pet_id>/photos", pets.pet_photos, name="pet-photos"),
    path("pets/<int:pet_id>/privacy", pets.pet_privacy, name="pet-privacy"),
    path("pets/<int:pet_id>/medical-records", pets.pet_medical_records, name="pet-medical-records"),
    path("pets/<int:pet_id>/vaccinations", pets.pet_vaccinations, name="pet-vaccinations"),
    path("pets/<int:pet_id>/lost/activate", pets.activate_lost_mode, name="pet-lost-activate"),
    path("nfc/tags/activate", nfc.activate_tag, name="nfc-activate-tag"),
    path("nfc/tags/deactivate", nfc.deactivate_tag, name="nfc-deactivate-tag"),
    path("nfc/scan/<str:tag_uid>", nfc.scan_tag, name="nfc-scan"),
    path("nfc/pets/<int:pet_id>/lost/close", nfc.close_lost_mode, name="nfc-lost-close"),
    path("nfc/pets/<int:pet_id>/found-report", nfc.create_found_report, name="nfc-found-report"),
    path("nfc/pets/<int:pet_id>/messages", nfc.pet_messages, name="nfc-messages"),
    path("content/categories", content.list_categories, name="content-categories"),
    path("content/categories/<str:slug>", content.get_category, name="content-category"),
    path("content/topics", content.topics, name="content-topics"),
    path("content/topics/<str:slug>", content.get_topic, name="content-topic"),
    path("content/topics/<str:slug>/faqs", content.topic_faqs, name="content-topic-faqs"),
    path("blog/posts", blog.posts, name="blog-posts"),
    path("blog/posts/<str:slug>", blog.post_detail, name="blog-post-detail"),
    path("blog/posts/<str:slug>/comments", blog.create_comment, name="blog-comment-create"),
    path("blog/posts/<str:slug>/like", blog.post_like, name="blog-like"),
    path("shop/categories", shop.list_categories, name="shop-categories"),
    path("shop/products", shop.products, name="shop-products"),
    path("shop/products/<str:slug>", shop.get_product, name="shop-product"),
    path("shop/cart", shop.get_cart, name="shop-cart"),
    path("shop/cart/items", shop.add_to_cart, name="shop-cart-add"),
    path("shop/cart/items/<int:item_id>", shop.remove_cart_item, name="shop-cart-remove"),
    path("shop/checkout", shop.checkout, name="shop-checkout"),
    path("shop/coupons/validate", shop.validate_coupon_code, name="shop-coupon-validate"),
    path("shop/payment-options", shop.payment_options, name="shop-payment-options"),
    path("shop/orders", shop.list_orders, name="shop-orders"),
    path("shop/orders/track", shop.track_order, name="shop-orders-track"),
    path("shop/orders/<int:order_id>", shop.get_order, name="shop-order-detail"),
    path(
        "shop/orders/<int:order_id>/payment-reference",
        shop.submit_payment_reference,
        name="shop-order-payment-reference",
    ),
    path(
        "shop/orders/<int:order_id>/pdf",
        shop.download_order_pdf,
        name="shop-order-pdf",
    ),
    path(
        "shop/payments/sslcommerz/success",
        shop.sslcommerz_success,
        name="shop-sslcommerz-success",
    ),
    path(
        "shop/payments/sslcommerz/fail",
        shop.sslcommerz_fail,
        name="shop-sslcommerz-fail",
    ),
    path(
        "shop/payments/sslcommerz/cancel",
        shop.sslcommerz_cancel,
        name="shop-sslcommerz-cancel",
    ),
    path(
        "shop/payments/sslcommerz/ipn",
        shop.sslcommerz_ipn,
        name="shop-sslcommerz-ipn",
    ),
    path("vendor/profile", vendor.vendor_profile, name="vendor-profile"),
    path("vendor/profile/logo", vendor.vendor_logo_upload, name="vendor-logo-upload"),
    path("vendor/products/image", vendor.vendor_product_image_upload, name="vendor-product-image-upload"),
    path("vendor/products", vendor.vendor_products, name="vendor-products"),
    path("vendor/products/<int:product_id>", vendor.vendor_product_detail, name="vendor-product-detail"),
    path(
        "vendor/products/<int:product_id>/stock",
        vendor.vendor_stock_adjust,
        name="vendor-product-stock",
    ),
    path(
        "vendor/products/<int:product_id>/movements",
        vendor.vendor_inventory_movements,
        name="vendor-product-movements",
    ),
    path("vendor/orders", vendor.vendor_orders, name="vendor-orders"),
    path("vendor/orders/<int:order_id>", vendor.vendor_order_detail, name="vendor-order-detail"),
    path("vendor/earnings", vendor.vendor_earnings, name="vendor-earnings"),
    path("vendor/payouts", vendor.vendor_payouts, name="vendor-payouts"),
    path("seller/invoices", invoices.seller_invoices, name="seller-invoices"),
    path("seller/invoices/defaults", invoices.seller_invoice_defaults, name="seller-invoice-defaults"),
    path(
        "seller/invoices/<int:order_id>",
        invoices.seller_invoice_detail,
        name="seller-invoice-detail",
    ),
    path(
        "seller/invoices/<int:order_id>/mark-paid",
        invoices.seller_invoice_mark_paid,
        name="seller-invoice-mark-paid",
    ),
    path("users/me/verifications", vendor.my_verifications, name="users-verifications"),
    path("users/me/verification", vendor.submit_verification, name="users-verification"),
    path("vets", vets.list_vets, name="vets-list"),
    path("vets/profile", vets.update_vet_profile, name="vets-profile"),
    path("vets/availability", vets.create_availability, name="vets-availability"),
    path(
        "vets/availability/<int:availability_id>",
        vets.delete_availability,
        name="vets-availability-delete",
    ),
    path("vets/appointments", vets.appointments, name="vets-appointments"),
    path("vets/appointments/<int:appointment_id>/status", vets.update_appointment_status, name="vets-appointment-status"),
    path("vets/appointments/<int:appointment_id>/notes", vets.create_consultation_note, name="vets-appointment-notes"),
    path("vets/<int:vet_id>", vets.get_vet, name="vets-detail"),
    path("marketplace/listings", marketplace.listings, name="marketplace-listings"),
    path("marketplace/listings/<int:listing_id>", marketplace.get_listing, name="marketplace-listing"),
    path("marketplace/listings/<int:listing_id>/report", marketplace.report_listing, name="marketplace-report"),
    path("admin/dashboard", admin.admin_dashboard, name="admin-dashboard"),
    path("admin/users", admin.list_users, name="admin-users"),
    path("admin/users/<int:user_id>/role", admin.update_user_role, name="admin-user-role"),
    path("admin/verifications", admin.list_verifications, name="admin-verifications"),
    path("admin/verifications/<int:request_id>/approve", admin.approve_verification, name="admin-verification-approve"),
    path("admin/verifications/<int:request_id>/reject", admin.reject_verification, name="admin-verification-reject"),
    path("admin/moderation", admin.list_moderation_queue, name="admin-moderation"),
    path("admin/moderation/<int:queue_id>/approve", admin.approve_moderation, name="admin-moderation-approve"),
    path("admin/moderation/<int:queue_id>/reject", admin.reject_moderation, name="admin-moderation-reject"),
    path("admin/orders", admin.list_all_orders, name="admin-orders"),
    path("admin/orders/<int:order_id>", admin.get_order, name="admin-order-detail"),
    path("admin/payments/pending", admin.list_pending_payments, name="admin-payments-pending"),
    path(
        "admin/orders/<int:order_id>/approve-payment",
        admin.approve_order_payment,
        name="admin-order-approve-payment",
    ),
    path(
        "admin/orders/<int:order_id>/status",
        admin.update_order_status,
        name="admin-order-status",
    ),
    path("admin/settings", admin.list_settings, name="admin-settings"),
    path("admin/settings/<str:key>", admin.update_setting, name="admin-setting-update"),
]
