# Generated by Django 6.0.6 on 2026-07-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity event', 'verbose_name_plural': 'Activity log'},
        ),
        migrations.AlterModelOptions(
            name='moderationqueue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review item', 'verbose_name_plural': 'Review queue'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Member notification', 'verbose_name_plural': 'Member inbox'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Brand setting', 'verbose_name_plural': 'Brand & settings'},
        ),
    ]
