# Generated by Django 6.0.6 on 2026-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('small_pet', 'Small Pet'), ('livestock', 'Livestock'), ('exotic', 'Exotic'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120, null=True)),
                ('color_markings', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age_text', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('spayed_neutered', models.BooleanField(blank=True, default=False, null=True)),
                ('temperament', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('instructions_if_found', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='accounts.user')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='PetHealthReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reminders', to='pets.pet')),
            ],
            options={
                'db_table': 'pet_health_reminders',
            },
        ),
        migrations.CreateModel(
            name='PetMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, null=True)),
                ('record_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet')),
            ],
            options={
                'db_table': 'pet_medical_records',
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pets.pet')),
            ],
            options={
                'db_table': 'pet_photos',
            },
        ),
        migrations.CreateModel(
            name='PetPrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('allow_call', models.BooleanField(default=False)),
                ('allow_whatsapp', models.BooleanField(default=False)),
                ('allow_chat', models.BooleanField(default=True)),
                ('show_city_only', models.BooleanField(default=True)),
                ('show_reward_note', models.BooleanField(default=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_setting', to='pets.pet')),
            ],
            options={
                'db_table': 'pet_privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateField()),
                ('medication_list', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pets.pet')),
                ('vet', models.ForeignKey(db_column='vet_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
                ('vet', models.ForeignKey(blank=True, db_column='vet_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'vaccinations',
            },
        ),
    ]
