# Generated by Django 6.0.6 on 2026-07-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vendorprofile'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(db_index=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=12, help_text='Take rate % on each sale.', max_digits=5)),
                ('listing_fee', models.DecimalField(decimal_places=2, default=0, help_text='Per-product listing fee (Etsy-style).', max_digits=10)),
                ('subscription_monthly_fee', models.DecimalField(decimal_places=2, default=0, help_text='Monthly seller subscription.', max_digits=10)),
                ('payment_processing_percent', models.DecimalField(decimal_places=2, default=2.9, max_digits=5)),
                ('payment_processing_fixed', models.DecimalField(decimal_places=2, default=0.3, max_digits=10)),
                ('applies_to', models.CharField(choices=[('all_sellers', 'All Third-Party Sellers'), ('tier_free', 'Free Tier Vendors'), ('tier_pro', 'Pro Tier Vendors'), ('tier_enterprise', 'Enterprise Tier Vendors')], default='all_sellers', max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'commission_plans',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='source_type',
            field=models.CharField(choices=[('platform_own', 'Kedi Smart Own Brand'), ('platform_brand', 'World Brand (Platform Stock)'), ('vendor', 'Third-Party Vendor')], default='platform_own', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='listing_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='source_type',
            field=models.CharField(choices=[('platform_own', 'Kedi Smart Own Brand'), ('platform_brand', 'World Brand (Platform Stock)'), ('vendor', 'Third-Party Vendor')], default='platform_own', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale Credit'), ('commission', 'Platform Commission'), ('listing_fee', 'Listing Fee'), ('payout', 'Payout'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='shop.orderitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.user')),
            ],
            options={
                'db_table': 'vendor_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.user')),
            ],
            options={
                'db_table': 'vendor_payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
