# Generated by Django 6.0.6 on 2026-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commissionplan_orderitem_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.CharField(choices=[('pet_animal', 'Pet & Animal'), ('general', 'General Products')], db_index=True, default='pet_animal', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='catalog',
            field=models.CharField(choices=[('pet_animal', 'Pet & Animal'), ('general', 'General Products')], db_index=True, default='pet_animal', max_length=20),
        ),
    ]
