# Generated by Django 6.0.6 on 2026-07-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_catalog_productcategory_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Public image path or URL. Prefer uploading in admin (auto-resized for shop).', max_length=500),
        ),
    ]
