# Generated by Django 6.0.6 on 2026-07-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login'),
        ('shop', '0005_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('delivery', 'Home Delivery'), ('store_pickup', 'Store Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='track_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_phone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_txn_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('ready_for_pickup', 'Ready for Pickup'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('STORE_PICKUP', 'Pay at Store Pickup'), ('Manual', 'Manual (legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('void', 'Void')], default='awaiting_payment', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_phone', models.CharField(max_length=60)),
                ('seller_email', models.CharField(blank=True, default='', max_length=255)),
                ('seller_address', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='shop.order')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('void', 'Void')], default='awaiting_payment', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_phone', models.CharField(max_length=60)),
                ('seller_email', models.CharField(blank=True, default='', max_length=255)),
                ('seller_address', models.TextField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='shop.invoice')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='shop.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='shop.payment')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-issued_at'],
            },
        ),
    ]
