# Generated by Django 6.0.6 on 2026-07-15 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login'),
        ('shop', '0006_invoice_receipt_payment_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('checkout', 'Online checkout'), ('manual', 'Manual / offline')], db_index=True, default='checkout', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='issuer',
            field=models.ForeignKey(blank=True, help_text='Seller who created a manual/offline invoice (vendor, vet, or live seller).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_orders', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'document_sequences',
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
