# Generated by Django 6.0.6 on 2026-07-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_login'),
        ('shop', '0007_seller_manual_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('physical', 'Physical product'), ('digital', 'Digital product'), ('service', 'Service')], db_index=True, default='physical', help_text='Physical products track units; services/digital typically do not.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='When false (services), stock is not decremented or checked.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Highlight low stock at or below this qty (Shopify-style reorder point).'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField(help_text='Positive = increase, negative = decrease')),
                ('quantity_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('manual_sale', 'Manual / POS sale'), ('restock', 'Restock / received'), ('adjustment', 'Manual adjustment'), ('return', 'Return / cancel restock'), ('initial', 'Initial stock')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='accounts.user')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='shop.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='shop.orderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='shop.productvariant')),
            ],
            options={
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
