# Generated by Django 6.0.6 on 2026-07-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
        ('shop', '0010_shipment_vendorstatement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipments_order_i_a07b5e_idx',
            old_name='shipments_order_i_idx',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='vendor_user_id', help_text='Null = platform-fulfilled stock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='vendorstatement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.user'),
        ),
    ]
