# Generated by Django 6.0.6 on 2026-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
        ('shop', '0011_selleraccount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'catalog', '-created_at'], name='product_status_cat_idx'),
        ),
    ]
