# Generated by Django 6.0.6 on 2026-07-19 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_finance_complete'),
        ('shop', '0012_product_product_status_cat_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionplan',
            name='setup_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time onboarding / setup fee charged when seller is approved.', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='COGS / unit cost for platform margin reporting.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendorledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('sale', 'Sale Credit'), ('commission', 'Platform Commission'), ('processing', 'Payment Processing Fee'), ('listing_fee', 'Listing Fee'), ('subscription', 'Seller Subscription'), ('setup_fee', 'One-time Setup Fee'), ('payout', 'Payout'), ('refund', 'Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_platform', models.BooleanField(db_index=True, default=False, help_text='True = platform company books; False = seller personal/business books.')),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('bill', 'Bill / payable'), ('income', 'Other income')], default='expense', max_length=20)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('supplies', 'Supplies'), ('shipping', 'Shipping / logistics'), ('marketing', 'Marketing'), ('payroll', 'Payroll'), ('tax', 'Tax'), ('cogs', 'Cost of goods'), ('software', 'Software / tools'), ('other', 'Other')], default='other', max_length=30)),
                ('number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('counterparty', models.CharField(blank=True, default='', help_text='Vendor/supplier (expense/bill) or payer (income).', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='posted', max_length=20)),
                ('issued_at', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_bills', to='accounts.user')),
            ],
            options={
                'db_table': 'expense_bills',
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('commission_income', 'Commission income'), ('listing_fee_income', 'Listing fee income'), ('subscription_income', 'Subscription income'), ('setup_fee_income', 'Setup fee income'), ('product_sales', 'Platform product sales'), ('processing_expense', 'Payment processing (est.)'), ('cogs', 'Cost of goods sold'), ('expense', 'Operating expense'), ('payout', 'Seller payout')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = income / asset; negative = expense / outflow.', max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_ledger_entries', to='shop.orderitem')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_ledger_entries', to='accounts.user')),
            ],
            options={
                'db_table': 'platform_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
