# Generated by Django 6.0.6 on 2026-07-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_finance_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daraz-style take rate for this category. Blank = use seller plan default.', max_digits=5, null=True),
        ),
    ]
