# Generated by Django 6.0.6 on 2026-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'animal_categories',
            },
        ),
        migrations.CreateModel(
            name='ContentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'content_tags',
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('canonical_url', models.CharField(blank=True, max_length=500, null=True)),
                ('og_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('json_ld_override', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seo_settings',
            },
        ),
        migrations.CreateModel(
            name='ContentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('body_md', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('vet_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, db_column='author_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.animalcategory')),
            ],
            options={
                'db_table': 'content_topics',
            },
        ),
        migrations.CreateModel(
            name='ContentTopicTag',
            fields=[
                ('pk', models.CompositePrimaryKey('topic', 'tag', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contenttag')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contenttopic')),
            ],
            options={
                'db_table': 'content_topic_tags',
            },
        ),
        migrations.AddField(
            model_name='contenttopic',
            name='tags',
            field=models.ManyToManyField(related_name='topics', through='content.ContentTopicTag', to='content.contenttag'),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.contenttopic')),
            ],
            options={
                'db_table': 'faq_items',
            },
        ),
    ]
