# Generated by Django 6.0.6 on 2026-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contenttopic',
            index=models.Index(fields=['status', 'category', '-published_at'], name='topic_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='seosetting',
            index=models.Index(fields=['entity_type', 'entity_id'], name='seo_entity_idx'),
        ),
    ]
