# Generated by Django 6.0.6 on 2026-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('clinic', 'Clinic')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='vets.appointment')),
                ('vet', models.ForeignKey(db_column='vet_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'consultation_notes',
            },
        ),
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255)),
                ('specialties', models.JSONField(blank=True, default=list, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('license_no', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('online_consultation_enabled', models.BooleanField(default=False)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'vet_profiles',
            },
        ),
        migrations.CreateModel(
            name='VetAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('clinic', 'Clinic')], max_length=20)),
                ('vet', models.ForeignKey(db_column='vet_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='vets.vetprofile', to_field='user')),
            ],
            options={
                'db_table': 'vet_availability',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(db_column='vet_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vets.vetprofile', to_field='user'),
        ),
    ]
