# Generated by Django 6.0.6 on 2026-07-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='clinic_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
