# Generated by Django 6.0.6 on 2026-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
        ('vets', '0002_add_clinic_image_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vetprofile',
            index=models.Index(fields=['verification_status', 'city'], name='vet_status_city_idx'),
        ),
    ]
