# Generated by Django 6.0.6 on 2026-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='blog_status_pub_idx'),
        ),
    ]
