# Generated by Django 6.0.6 on 2026-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_selleraccount'),
        ('marketplace', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='petlisting',
            index=models.Index(fields=['status', '-created_at'], name='listing_status_date_idx'),
        ),
    ]
