# Generated by Django 6.0.6 on 2026-07-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_petlisting_listing_status_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlisting',
            name='listing_fee_paid',
            field=models.BooleanField(default=False, help_text='True after live-animal listing insertion fee is charged.'),
        ),
    ]
