# Generated by Django 6.0.6 on 2026-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('finder_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'db_table': 'found_reports',
            },
        ),
        migrations.CreateModel(
            name='LostPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_location_text', models.TextField()),
                ('last_seen_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen_lng', models.CharField(blank=True, max_length=50, null=True)),
                ('reward_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('found', 'Found'), ('closed', 'Closed')], default='active', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'db_table': 'lost_pet_reports',
            },
        ),
        migrations.CreateModel(
            name='MaskedMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finder_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
            options={
                'db_table': 'masked_message_threads',
            },
        ),
        migrations.CreateModel(
            name='MaskedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('owner', 'Owner'), ('finder', 'Finder')], max_length=20)),
                ('message', models.TextField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nfc.maskedmessagethread')),
            ],
            options={
                'db_table': 'masked_messages',
            },
        ),
        migrations.CreateModel(
            name='NFCTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_uid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nfc_url', models.CharField(blank=True, max_length=500, null=True)),
                ('qr_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('lost', 'Lost'), ('retired', 'Retired')], default='available', max_length=20)),
                ('sku_product', models.ForeignKey(blank=True, db_column='sku_product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'db_table': 'nfc_tags',
            },
        ),
        migrations.CreateModel(
            name='TagActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='nfc.nfctag')),
            ],
            options={
                'db_table': 'tag_activations',
            },
        ),
    ]
